version: "3.8"

services:
  gsky_memcached:
    image: memcached:1.6.12-alpine
    container_name: gsky_memcached
    restart: ${RESTART_POLICY}
    ports:
     - 11211
  gsky_ows:
    image: africahazardswatch.org/gsky-ows:latest
    container_name: gsky_ows
    build:
      context: ./ows
      args:
        gsky_repo: ${GSKY_REPO}
        gsky_branch: ${GSKY_BRANCH}
    restart: ${RESTART_POLICY}
    volumes:
      - ${GSKY_CONFIG_VOLUME}:/gsky/etc
      - ./ows/rulesets:/rulesets
      - ./ows/templates/WPS:/templates/WPS
      - ./ows/templates/WMS_GetCapabilities.tpl:/gsky/share/gsky/templates/WMS_GetCapabilities.tpl
      - ./ows/templates/WPS_GetCapabilities.tpl:/gsky/share/gsky/templates/WPS_GetCapabilities.tpl
      - ./ows/templates/WCS_GetCapabilities.tpl:/gsky/share/gsky/templates/WCS_GetCapabilities.tpl
    environment: 
      - WAIT_HOSTS=gsky_mas_db:5432, gsky_rpc_1:6000, gsky_rpc_2:6000
      - WAIT_TIMEOUT=120
      - OWS_HOSTNAME=${GSKY_OWS_HOSTNAME}
      - OWS_PROTOCOL=${GSKY_OWS_PROTOCOL}
      - MAS_ADDRESS=gsky_mas_api:8888
      - WORKER_NODES="gsky_rpc_1:6000","gsky_rpc_2:6000"
      - WEBHOOK_SECRET=${GSKY_WEBHOOK_SECRET}
      - WEBHOOK_ENABLED=true
      - MEMCACHE_URI=gsky_memcached:11211
    ports:
      - 8080
      - 9000
  gsky_mas_db:
    image: postgis/postgis:12-master
    container_name: gsky_mas_db
    restart: ${RESTART_POLICY}
    volumes:
        - ${GSKY_MAS_DB_VOLUME}:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${GSKY_MAS_DB_PASSWORD}
      - POSTGRES_DB=mas
  gsky_mas_api:
    image: africahazardswatch.org/gsky-mas:latest
    container_name: gsky_mas_api
    build:
      context: ./mas_api
      args:
        gsky_repo: ${GSKY_REPO}
        gsky_branch: ${GSKY_BRANCH}
    restart: ${RESTART_POLICY}
    volumes:
      - ${GSKY_DATA_VOLUME}:/gskydata
      - ./mas_api/scripts/ingest.sh:/ingest.sh
      - .${GSKY_INGEST_SCRIPTS_VOLUME}:/ingest_scripts
      - ./ows/rulesets:/rulesets
    environment:
      - WAIT_HOSTS=gsky_mas_db:5432
      - WAIT_TIMEOUT=120
      - PGHOST=gsky_mas_db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=${GSKY_MAS_DB_PASSWORD}
      - PGDB=mas
      - WEBHOOK_SECRET=${GSKY_WEBHOOK_SECRET}
      - WEBHOOK_ENABLED=true
    ports:
      - 8888
      - 9000
  gsky_rpc_1:
    image: africahazardswatch.org/gsky-rpc:latest
    container_name: gsky_rpc_1
    build:
      context: ./rpc
      args:
        gsky_repo: ${GSKY_REPO}
        gsky_branch: ${GSKY_BRANCH}
    restart: ${RESTART_POLICY}
    volumes:
      - ${GSKY_DATA_VOLUME}:/gskydata
    environment:
      - WAIT_HOSTS=gsky_mas_db:5432
      - WAIT_TIMEOUT=120
    ports:
      - 6000
  gsky_rpc_2:
      image: africahazardswatch.org/gsky-rpc:latest
      container_name: gsky_rpc_2
      build:
        context: ./rpc
        args:
          gsky_repo: ${GSKY_REPO}
          gsky_branch: ${GSKY_BRANCH}
      restart: ${RESTART_POLICY}
      volumes:
        - ${GSKY_DATA_VOLUME}:/gskydata
      environment:
        - WAIT_HOSTS=gsky_mas_db:5432
        - WAIT_TIMEOUT=120
      ports:
        - 6000
  # gsky_rpc_3:
  #     image: africahazardswatch.org/gsky-rpc:latest
  #     container_name: gsky_rpc_3
  #     build:
  #       context: ./rpc
  #       args:
  #         gsky_repo: ${GSKY_REPO}
  #         gsky_branch: ${GSKY_BRANCH}
  #     restart: ${RESTART_POLICY}
  #     volumes:
  #       - ${GSKY_DATA_VOLUME}:/gskydata
  #     environment:
  #       - WAIT_HOSTS=gsky_mas_db:5432
  #       - WAIT_TIMEOUT=120
  #     ports:
  #       - 6000
  # gsky_rpc_4:
  #     image: africahazardswatch.org/gsky-rpc:latest
  #     container_name: gsky_rpc_4
  #     build:
  #       context: ./rpc
  #       args:
  #         gsky_repo: ${GSKY_REPO}
  #         gsky_branch: ${GSKY_BRANCH}
  #     restart: ${RESTART_POLICY}
  #     volumes:
  #       - ${GSKY_DATA_VOLUME}:/gskydata
  #     environment:
  #       - WAIT_HOSTS=gsky_mas_db:5432
  #       - WAIT_TIMEOUT=120
  #     ports:
  #       - 6000
  gsky_wps_client:
      image: africahazardswatch.org/gsky-wps-client:latest
      container_name: gsky_wps_client
      build:
        context: ./ows_wps_client
        args:
          wps_client_repo: ${WPS_CLIENT_REPO}
          wps_client_repo_branch: ${WPS_CLIENT_REPO_BRANCH}
      restart: ${RESTART_POLICY}
      environment:
        - WAIT_HOSTS=gsky_mas_db:5432
        - WAIT_TIMEOUT=120
        - GSKY_OWS_URL=http://gsky_ows:8080/ows
        - GSKY_MAS_URL=http://gsky_mas_api:8888
        - TIMEOUT_SECONDS=${WPS_CLIENT_TIMEOUT_SECONDS}
      ports:
        - 3000
  gsky_nginx:
      image: africahazardswatch.org/gsky-nginx:latest
      build:
        context: ./nginx
      container_name: gsky_nginx
      command: sh -c "/wait && nginx -g 'daemon off;'"
      restart: ${RESTART_POLICY}
      environment:
        - WAIT_HOSTS=gsky_ows:8080, gsky_mas_api:8888, gsky_wps_client:3000
        - WAIT_TIMEOUT=120
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - ${GSKY_NGINX_PORT}:80
networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true